version: '3'  
services:  
  vote:
    image: instavote/vote
    deploy:
      replicas: 2
    networks:
      - myoverlay
    ports:
      - 80

  proxy:
    image: nginx:latest
    ports:
        - 8080:80
    networks:
      - myoverlay
    command: |
      /bin/bash -c "echo '
      server {
        listen 80;
        add_header X-Frame-Options "SAMEORIGIN";
        location / {
            proxy_pass http://vote:80;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  myoverlay: 
    driver: overlay
